services:
  backend:
    container_name: backend
    build:
      context: ./backend/chatProject/
    volumes:
      - ./backend/chatProject:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=chatProject.settings
    networks:
      - webnet

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - webnet

networks:
  webnet:
